### ISSUE TITLE
Impose cache line alignment in class node instances

### ISSUE THREAD

**Issue by jbelloncastro** [jbelloncastro/hashtree#1]
Overload operator new and delete.

Example:
https://software.intel.com/en-us/forums/intel-c-compiler/topic/328882

**Comment by metbosch** [comment]
Fixed in commit  0e813af1419c6a60cc1df893dd3d834d45f312a8.
Using the `alignas` specifier (http://en.cppreference.com/w/cpp/language/alignas).
